#pragma config(Sensor, S1,     ,               sensorEV3_Touch)
#pragma config(Sensor, S4,     button1,        sensorEV3_Touch)
#pragma config(Motor,  motorA,          a,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          b,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          c,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          d,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[b]=100;
	motor[A]=100;
	wait1msec(10000);


{
		motor[b]=-100;
		motor[A]=-100;
		wait1msec(10000);


}

	{
	 while(SensorValue)(button1) ==1)
	}
{
	motor(motorA)= 100;
	motor(motorB)= 100;

}



}
