#pragma config(Sensor, S1,     ,               sensorEV3_Touch)
#pragma config(Sensor, S4,     button1,        sensorEV3_Touch)
#pragma config(Motor,  motorA,          a,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          b,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          c,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          d,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


















task main()
{
	int mode = 0
	int speed = 15;
	int speed2 = 5;

	if(mode = 1)
	{
		motor(motorb) = speed
		motor(motora) = speed2
		wait1msec(500);

		speed = speed + 10;
		speed2 = speed2 + 10;

	if(sensorvalue(button1) == 0)
		{
			(mode = 1)
		}
		if(sensorvalue(button1) == 1)
			{
				(mode = 2)
			}
		}
				if(mode = 2)
				{
					motor(motorA) =-90;
					motor(motorB) =-50;
					Wait1msec(1000);
					motor(motorB) =50;
					motor(motorA) =60;
					Wait1msec(12000);
				}


}
